name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependency pnpm
        run: pnpm install --frozen-lockfile

      - name: Test Package
        run: pnpm test

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependency pnpm
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: publish package
        run: npm publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
